### ISSUE TITLE
[Idea] YouTube video on music play

### ISSUE THREAD

**Issue by RianOBrian** [IdolKeg/AnimaPaper#12]
Hi,

I just found this and already have fallen in love with it. I just had the idea of listening to music playing and connecting to iTunes, Spotify, etc to get the name and artist. The app could then get the official video off YouTube and play that (as an MP4) as the background.

Is this a good idea?

Thanks,
Rian.

**Comment by IdolKeg** [comment]
Hello,
It's a good idea indeed. As for me, I'd like people to add the feature they want :) I made it open source and free for this purpose. I almost finish my paper and I will have to find a job soon, I have other projects as well I'm working on.
It is good idea that you have, but I will focus on the most requested features first and hope that some devs are willing to give a hand and work on improving it as well.

Thanks for the idea @RianOBrian, I will add it to the features so people can see it and devs know which features people want :)

**Comment by RianOBrian** [comment]
Alright, thanks.

I would add it myself if it were in Java but I don't know C# (yet) so I can't help, sorry.

**Comment by IdolKeg** [comment]
C# is very similar to Java so you would probably learn it in a week end. Of course there are few big differences but the core thing is almost the same, just the syntax differs.

(You can also fork it and make a java version ;)

**Comment by RianOBrian** [comment]
AFAIK, Java isn't able to do the same things as C# and isn't able to get the permissions from Windows that are required. Am I correct?

**Comment by IdolKeg** [comment]
I think someone sent me a message on Reddit after I started that he made a java version that worked pretty much the same as mine.
As I am not a Java enthusiast and even less a professional, I cannot tell if it's true or not.
