### ISSUE TITLE
UI for multiple monitors (different from display problem)

### ISSUE THREAD

**Issue by tyopoyt** [IdolKeg/AnimaPaper#13]
I just downloaded the latest release of the software and the options for setting monitor videos is now missing, and the all monitors button is greyed out.

I tried restarting my system with "Run at Startup" both selected and deselected, but the behavior persists.
The older release I have still shows these options.  I'll attach pics of both to this post.

(P.S. Just to clarify, the known issue displaying on multiple monitors is still occurring, I just am reporting this separate issue.)

Newest release:
![capture](https://cloud.githubusercontent.com/assets/26366348/23835378/acd88d3e-073c-11e7-8c03-4b4177fd4aba.PNG)

Older release:
![capture](https://cloud.githubusercontent.com/assets/26366348/23835386/cbbb60fa-073c-11e7-901b-6cefac57b0be.PNG)

**Comment by IdolKeg** [comment]
It's not missing, I commented the code in the current release as it's not working for now. 
What I intended to do in the version you show me is that every monitor can display a different wallpaper, which is not the case for now. That's why I commented the code in the current release.

**Comment by ScottBeeson** [comment]
You should also have commented the "Multiple Monitors" checkbox, right?

**Comment by IdolKeg** [comment]
Indeed, I should have commented it in the UI.
