### ISSUE TITLE
Can't properly setup project

### ISSUE THREAD

**Issue by SirWindfield** [IdolKeg/AnimaPaper#2]
Hey there :)

I have some ideas for the application but I cannot properly setup the project on my PC. I am new to Visual Studio so ye. For some odd reason the .ico file does not get copied into the output folder of the project, meaning that the project fails on creating the icon in the constructor of the MainWindow class.

**Comment by SirWindfield** [comment]
nvm my fault.

**Comment by IdolKeg** [comment]
Hello,

Good that you find the problem :)
