### ISSUE TITLE
Can not be run with teamviewer or windows7

### ISSUE THREAD

**Issue by TGSAN** [IdolKeg/AnimaPaper#5]
Hello, IdolKeg. This program can not be run with teamviewer, because teamviewer killed WorkerW，how to reboot the WorkerW same like Wallpaper Engine，In addition, on Windows7 can be set on the Program Manager as the parent window to run the program under the desktop icon.（I'm sorry, my English is not good）

**Comment by IdolKeg** [comment]
Hello TGSAN.
Yes it cannot run at the same time as TeamViewer for now, I will have to look on how to reboot it.
Thanks for the tip about windows 7, I will also check that as soon as I can :)

**Comment by TGSAN** [comment]
Thank you
