### ISSUE TITLE
pause in video loop

### ISSUE THREAD

**Issue by Tsoccerguy3** [IdolKeg/AnimaPaper#6]
BUG
All video loops , have a slight pause in the cycle . This makes it very distracting as a desktop. When these loops are played in Star-docks Dream-scenes , there is no pause and the video loop cycles flawlessly . There should be a pre - buffer to stop this stutter . BUG

**Comment by IdolKeg** [comment]
Mmh I know that there is a slight pause but I didn't had time before my motherboard burnt to have a look at it unfortunately.
I will see what can be done when I will have my own computer again.
