### ISSUE TITLE
White screen with *.mpg video

### ISSUE THREAD

**Issue by Tsoccerguy3** [IdolKeg/AnimaPaper#7]
It cant play mpg video on windows 10

General
Format                         : MPEG Video
Format version                 : Version 2
File size                      : 10.6 MiB
Duration                       : 6 s 160 ms
Overall bit rate mode          : Variable
Overall bit rate               : 14.4 Mb/s
Writing library                : TMPGEnc XPress 4.6.2.266

Video
Format                         : MPEG Video
Format version                 : Version 2
Format profile                 : Main@High
Format settings, BVOP          : Yes
Format settings, Matrix        : Custom
Format settings, GOP           : M=3, N=18
Duration                       : 6 s 160 ms
Bit rate mode                  : Variable
Bit rate                       : 14.4 Mb/s
Maximum bit rate               : 18.0 Mb/s
Width                          : 1 280 pixels
Height                         : 800 pixels
Display aspect ratio           : 16:10
Frame rate                     : 25.000 FPS
Standard                       : NTSC
Color space                    : YUV
Chroma subsampling             : 4:2:0
Bit depth                      : 8 bits
Scan type                      : Progressive
Compression mode               : Lossy
Bits/(Pixel*Frame)             : 0.563
Time code of first frame       : 00:00:00:00
GOP, Open/Closed               : Open
GOP, Open/Closed of first fram : Closed
Stream size                    : 10.6 MiB (100%)
Writing library                : TMPGEnc XPress 4.6.2.266
Color primaries                : BT.601 NTSC
Transfer characteristics       : BT.601
Matrix coefficients            : BT.601

**Comment by IdolKeg** [comment]
Alright, so I tried with MPEG-1 and MPEG-2 files.
Version 1 is working as intended, version 2 shows blank screen.
Thanks for the report.

**Comment by IdolKeg** [comment]
So I did some research and I found it.
https://support.microsoft.com/en-us/help/316992/file-types-supported-by-windows-media-player
Since my program use the native windows media player in windows and this one doesn't support MPEG-2 files, that's why you get blank screen. 

I didn't try but I guess if you install some codecs for windows media player that support this file it will work.
