### ISSUE TITLE
Add set as wallpaper support  to context menu and other Windows wallpaper support

### ISSUE THREAD

**Issue by Tsoccerguy3** [IdolKeg/AnimaPaper#8]
It would be a good idea to allow , right click on video , Set as Wallpaper . Even dedicated extension support for video loops . and play - lists support . A lot of these features are already integrated into windows 10 . 

like - *.loop , double clicking a "video.loop" would set as wallpaper .

**Comment by IdolKeg** [comment]
Oh right, I didn't think about that.
Let me add it to the list of features.
Thanks :)
